In [2]:
import pandas as pd
import numpy as np

print("Projet WC2026 ML lancé 🚀")

Projet WC2026 ML lancé 🚀

In [3]:
import pandas as pd
import numpy as np

# Charger le dataset
df = pd.read_csv("../data/results.csv")

# Afficher les 5 premières lignes
df.head()

,date,home_team,away_team,home_score,away_score,tournament,city,country,neutral
0,1872-11-30,Scotland,England,0.0,0.0,Friendly,Glasgow,Scotland,False
1,1873-03-08,England,Scotland,4.0,2.0,Friendly,London,England,False
2,1874-03-07,Scotland,England,2.0,1.0,Friendly,Glasgow,Scotland,False
3,1875-03-06,England,Scotland,2.0,2.0,Friendly,London,England,False
4,1876-03-04,Scotland,England,3.0,0.0,Friendly,Glasgow,Scotland,False

In [4]:
print(df.shape)

(49437, 9)

In [5]:
print(df.columns)

Index(['date', 'home_team', 'away_team', 'home_score', 'away_score',
       'tournament', 'city', 'country', 'neutral'],
      dtype='str')

In [6]:
df.sample(5)

,date,home_team,away_team,home_score,away_score,tournament,city,country,neutral
12299,1980-06-29,Tunisia,Nigeria,2.0,0.0,FIFA World Cup qualification,Tunis,Tunisia,False
18682,1992-12-07,Bahrain,Oman,3.0,0.0,Gulf Cup,Doha,Qatar,True
25748,2001-07-01,Uruguay,Brazil,1.0,0.0,FIFA World Cup qualification,Montevideo,Uruguay,False
37233,2013-09-06,Mexico,Honduras,1.0,2.0,FIFA World Cup qualification,Mexico City,Mexico,False
32253,2008-08-20,Turkey,Chile,1.0,0.0,Friendly,İzmit,Turkey,False

In [7]:
df = df[[
    "date",
    "home_team",
    "away_team",
    "home_score",
    "away_score",
    "tournament"
]]

In [8]:
df.sample(5)

,date,home_team,away_team,home_score,away_score,tournament
40615,2017-06-05,DR Congo,Botswana,2.0,0.0,Friendly
8548,1971-09-12,South Korea,Iran,0.0,2.0,Friendly
12573,1980-12-12,Curaçao,Haiti,1.0,1.0,CONCACAF Championship qualification
32098,2008-06-21,South Africa,Sierra Leone,0.0,0.0,FIFA World Cup qualification
7608,1969-02-08,Zimbabwe,Malawi,4.0,0.0,Friendly

In [9]:
def get_result(row):

    # Si l'équipe domicile marque plus
    if row["home_score"] > row["away_score"]:
        return 0

    # Si l'équipe extérieure marque plus
    elif row["home_score"] < row["away_score"]:
        return 2

    # Sinon match nul
    else:
        return 1

In [10]:
# Appliquer la fonction "get_result" à chaque ligne du DataFrame

In [11]:
df["result"] = df.apply(get_result, axis=1)

In [12]:
df.head()

         date home_team away_team  home_score  away_score tournament  result
0  1872-11-30  Scotland   England         0.0         0.0   Friendly       1
1  1873-03-08   England  Scotland         4.0         2.0   Friendly       0
2  1874-03-07  Scotland   England         2.0         1.0   Friendly       0
3  1875-03-06   England  Scotland         2.0         2.0   Friendly       1
4  1876-03-04  Scotland   England         3.0         0.0   Friendly       0

In [13]:
df["result"].value_counts()

result
0    24192
2    13948
1    11297
Name: count, dtype: int64

In [14]:
teams_stats = {}

In [15]:
for _, row in df.iterrows():

    home = row["home_team"]
    away = row["away_team"]

    if home not in teams_stats:
        teams_stats[home] = {
            "matches": 0,
            "wins": 0
        }

    if away not in teams_stats:
        teams_stats[away] = {
            "matches": 0,
            "wins": 0
        }

    teams_stats[home]["matches"] += 1
    teams_stats[away]["matches"] += 1

    if row["result"] == 0:
        teams_stats[home]["wins"] += 1

    elif row["result"] == 2:
        teams_stats[away]["wins"] += 1