In [18]:
import pandas as pd
import numpy as np

print("Projet WC2026 ML lancé 🚀")

Projet WC2026 ML lancé 🚀

In [19]:
import pandas as pd
import numpy as np

# Charger le dataset
df = pd.read_csv("../data/results.csv")

# Afficher les 5 premières lignes
df.head()

,date,home_team,away_team,home_score,away_score,tournament,city,country,neutral
0,1872-11-30,Scotland,England,0.0,0.0,Friendly,Glasgow,Scotland,False
1,1873-03-08,England,Scotland,4.0,2.0,Friendly,London,England,False
2,1874-03-07,Scotland,England,2.0,1.0,Friendly,Glasgow,Scotland,False
3,1875-03-06,England,Scotland,2.0,2.0,Friendly,London,England,False
4,1876-03-04,Scotland,England,3.0,0.0,Friendly,Glasgow,Scotland,False

In [20]:
print(df.shape)

(49437, 9)

In [21]:
print(df.columns)

Index(['date', 'home_team', 'away_team', 'home_score', 'away_score',
       'tournament', 'city', 'country', 'neutral'],
      dtype='str')

In [22]:
df.sample(5)

,date,home_team,away_team,home_score,away_score,tournament,city,country,neutral
14145,1984-06-02,Portugal,Yugoslavia,2.0,3.0,Friendly,Oeiras,Portugal,False
25874,2001-08-15,Norway,Turkey,1.0,1.0,Friendly,Oslo,Norway,False
8134,1970-08-06,Hong Kong,Singapore,3.0,2.0,Merdeka Tournament,Kuala Lumpur,Malaysia,True
5305,1961-06-25,Poland,Yugoslavia,1.0,1.0,FIFA World Cup qualification,Chorzów,Poland,False
32626,2008-12-07,Grenada,Barbados,4.0,2.0,CFU Caribbean Cup,Falmouth,Jamaica,True

In [23]:
df = df[[
    "date",
    "home_team",
    "away_team",
    "home_score",
    "away_score",
    "tournament"
]]

In [24]:
df.sample(5)

,date,home_team,away_team,home_score,away_score,tournament
48661,2025-09-09,Tanzania,Niger,0.0,1.0,FIFA World Cup qualification
8732,1972-01-09,Burkina Faso,Nigeria,3.0,3.0,Friendly
19820,1994-07-08,Solomon Islands,New Caledonia,3.0,1.0,Melanesia Cup
19568,1994-02-23,Saint Kitts and Nevis,Montserrat,9.0,1.0,CFU Caribbean Cup qualification
31419,2007-11-02,Saudi Arabia,Namibia,1.0,0.0,Friendly

In [25]:
def get_result(row):

    # Si l'équipe domicile marque plus
    if row["home_score"] > row["away_score"]:
        return 0

    # Si l'équipe extérieure marque plus
    elif row["home_score"] < row["away_score"]:
        return 2

    # Sinon match nul
    else:
        return 1

In [26]:
# Appliquer la fonction "get_result" à chaque ligne du DataFrame

In [27]:
df["result"] = df.apply(get_result, axis=1)

In [28]:
df.head()

         date home_team away_team  home_score  away_score tournament  result
0  1872-11-30  Scotland   England         0.0         0.0   Friendly       1
1  1873-03-08   England  Scotland         4.0         2.0   Friendly       0
2  1874-03-07  Scotland   England         2.0         1.0   Friendly       0
3  1875-03-06   England  Scotland         2.0         2.0   Friendly       1
4  1876-03-04  Scotland   England         3.0         0.0   Friendly       0

In [29]:
df["result"].value_counts()

result
0    24192
2    13948
1    11297
Name: count, dtype: int64

In [30]:
teams_stats = {}

In [31]:
for _, row in df.iterrows():

    home = row["home_team"]
    away = row["away_team"]

    if home not in teams_stats:
        teams_stats[home] = {
            "matches": 0,
            "wins": 0
        }

    if away not in teams_stats:
        teams_stats[away] = {
            "matches": 0,
            "wins": 0
        }

    teams_stats[home]["matches"] += 1
    teams_stats[away]["matches"] += 1

    if row["result"] == 0:
        teams_stats[home]["wins"] += 1

    elif row["result"] == 2:
        teams_stats[away]["wins"] += 1

In [32]:
teams_stats["France"]

{'matches': 937, 'wins': 476}

In [33]:
for team in teams_stats:

    matches = teams_stats[team]["matches"]
    wins = teams_stats[team]["wins"]

    teams_stats[team]["win_rate"] = wins / matches