In [60]:
import pandas as pd
import numpy as np

print("Projet WC2026 ML lancé 🚀")

Projet WC2026 ML lancé 🚀

In [61]:
import pandas as pd
import numpy as np

# Charger le dataset
df = pd.read_csv("../data/results.csv")

# Afficher les 5 premières lignes
df.head()

,date,home_team,away_team,home_score,away_score,tournament,city,country,neutral
0,1872-11-30,Scotland,England,0.0,0.0,Friendly,Glasgow,Scotland,False
1,1873-03-08,England,Scotland,4.0,2.0,Friendly,London,England,False
2,1874-03-07,Scotland,England,2.0,1.0,Friendly,Glasgow,Scotland,False
3,1875-03-06,England,Scotland,2.0,2.0,Friendly,London,England,False
4,1876-03-04,Scotland,England,3.0,0.0,Friendly,Glasgow,Scotland,False

In [62]:
print(df.shape)

(49437, 9)

In [63]:
print(df.columns)

Index(['date', 'home_team', 'away_team', 'home_score', 'away_score',
       'tournament', 'city', 'country', 'neutral'],
      dtype='str')

In [64]:
df.sample(5)

,date,home_team,away_team,home_score,away_score,tournament,city,country,neutral
21583,1996-12-14,Northern Ireland,Albania,2.0,0.0,FIFA World Cup qualification,Belfast,Northern Ireland,False
48306,2025-06-01,El Salvador,Guatemala,1.0,1.0,Friendly,Chattanooga,United States,True
45988,2023-03-28,Bahrain,Syria,1.0,0.0,Friendly,Arad,Bahrain,False
47897,2024-11-14,South Sudan,Congo,3.0,2.0,African Cup of Nations qualification,Juba,South Sudan,False
25864,2001-08-15,Estonia,Cyprus,2.0,2.0,FIFA World Cup qualification,Tallinn,Estonia,False

In [65]:
df = df[[
    "date",
    "home_team",
    "away_team",
    "home_score",
    "away_score",
    "tournament"
]]

In [66]:
df.sample(5)

,date,home_team,away_team,home_score,away_score,tournament
6807,1966-11-01,Ivory Coast,Ghana,1.0,1.0,Friendly
2320,1938-05-21,Netherlands,Scotland,1.0,3.0,Friendly
12265,1980-06-13,Algeria,Sierra Leone,3.0,1.0,FIFA World Cup qualification
21400,1996-10-06,Gabon,Cameroon,0.0,0.0,African Cup of Nations qualification
11376,1978-05-24,England,Hungary,4.0,1.0,Friendly

In [67]:
def get_result(row):

    # Si l'équipe domicile marque plus
    if row["home_score"] > row["away_score"]:
        return 0

    # Si l'équipe extérieure marque plus
    elif row["home_score"] < row["away_score"]:
        return 2

    # Sinon match nul
    else:
        return 1

In [68]:
# Appliquer la fonction "get_result" à chaque ligne du DataFrame

In [69]:
df["result"] = df.apply(get_result, axis=1)

In [70]:
df.head()

         date home_team away_team  home_score  away_score tournament  result
0  1872-11-30  Scotland   England         0.0         0.0   Friendly       1
1  1873-03-08   England  Scotland         4.0         2.0   Friendly       0
2  1874-03-07  Scotland   England         2.0         1.0   Friendly       0
3  1875-03-06   England  Scotland         2.0         2.0   Friendly       1
4  1876-03-04  Scotland   England         3.0         0.0   Friendly       0

In [71]:
df["result"].value_counts()

result
0    24192
2    13948
1    11297
Name: count, dtype: int64

In [72]:
teams_stats = {}

In [73]:
for _, row in df.iterrows():

    home = row["home_team"]
    away = row["away_team"]

    if home not in teams_stats:
        teams_stats[home] = {
            "matches": 0,
            "wins": 0
        }

    if away not in teams_stats:
        teams_stats[away] = {
            "matches": 0,
            "wins": 0
        }

    teams_stats[home]["matches"] += 1
    teams_stats[away]["matches"] += 1

    if row["result"] == 0:
        teams_stats[home]["wins"] += 1

    elif row["result"] == 2:
        teams_stats[away]["wins"] += 1

In [74]:
teams_stats["France"]

{'matches': 937, 'wins': 476}

In [75]:
for team in teams_stats:

    matches = teams_stats[team]["matches"]
    wins = teams_stats[team]["wins"]

    teams_stats[team]["win_rate"] = wins / matches

In [76]:
teams_stats["France"]

{'matches': 937, 'wins': 476, 'win_rate': 0.5080042689434365}

In [77]:
def get_team_win_rate(team):
    return teams_stats[team]["win_rate"]

In [78]:
df["home_win_rate"] = df["home_team"].apply(get_team_win_rate)

df["away_win_rate"] = df["away_team"].apply(get_team_win_rate)

In [79]:
df[[
    "home_team",
    "away_team",
    "home_win_rate",
    "away_win_rate",
    "result"
]].head()

  home_team away_team  home_win_rate  away_win_rate  result
0  Scotland   England       0.470726       0.571429       1
1   England  Scotland       0.571429       0.470726       0
2  Scotland   England       0.470726       0.571429       0
3   England  Scotland       0.571429       0.470726       1
4  Scotland   England       0.470726       0.571429       0