In [2]:
import pandas as pd
import numpy as np

print("Projet WC2026 ML lancé 🚀")

Projet WC2026 ML lancé 🚀

In [1]:
import pandas as pd
import numpy as np

# Charger le dataset
df = pd.read_csv("../data/results.csv")

# Afficher les 5 premières lignes
df.head()

,date,home_team,away_team,home_score,away_score,tournament,city,country,neutral
0,1872-11-30,Scotland,England,0.0,0.0,Friendly,Glasgow,Scotland,False
1,1873-03-08,England,Scotland,4.0,2.0,Friendly,London,England,False
2,1874-03-07,Scotland,England,2.0,1.0,Friendly,Glasgow,Scotland,False
3,1875-03-06,England,Scotland,2.0,2.0,Friendly,London,England,False
4,1876-03-04,Scotland,England,3.0,0.0,Friendly,Glasgow,Scotland,False

In [2]:
print(df.shape)

(49437, 9)

In [3]:
print(df.columns)

Index(['date', 'home_team', 'away_team', 'home_score', 'away_score',
       'tournament', 'city', 'country', 'neutral'],
      dtype='str')

In [4]:
df.sample(5)

,date,home_team,away_team,home_score,away_score,tournament,city,country,neutral
19378,1993-10-10,Morocco,Zambia,1.0,0.0,FIFA World Cup qualification,Casablanca,Morocco,False
45301,2022-06-08,Wales,Netherlands,1.0,2.0,UEFA Nations League,Cardiff,Wales,False
41206,2017-11-14,South Korea,Serbia,1.0,1.0,Friendly,Ulsan,South Korea,False
10609,1976-08-07,Malaysia,South Korea,2.0,1.0,Merdeka Tournament,Kuala Lumpur,Malaysia,False
21993,1997-06-01,Malta,Scotland,2.0,3.0,Friendly,Attard,Malta,False

In [5]:
df = df[[
    "date",
    "home_team",
    "away_team",
    "home_score",
    "away_score",
    "tournament"
]]

In [6]:
df.sample(5)

,date,home_team,away_team,home_score,away_score,tournament
3484,1951-03-07,Northern Ireland,Wales,1.0,2.0,British Home Championship
25921,2001-09-02,Jamaica,Mexico,1.0,2.0,FIFA World Cup qualification
26091,2001-12-05,Algeria,Ghana,1.0,1.0,Friendly
38097,2014-09-25,Indonesia,Cambodia,1.0,0.0,Friendly
22202,1997-07-27,Iceland,Faroe Islands,1.0,0.0,Friendly