In [40]:
import pandas as pd
import numpy as np

print("Projet WC2026 ML lancé 🚀")

Projet WC2026 ML lancé 🚀

In [41]:
import pandas as pd
import numpy as np

# Charger le dataset
df = pd.read_csv("../data/results.csv")

# Afficher les 5 premières lignes
df.head()

,date,home_team,away_team,home_score,away_score,tournament,city,country,neutral
0,1872-11-30,Scotland,England,0.0,0.0,Friendly,Glasgow,Scotland,False
1,1873-03-08,England,Scotland,4.0,2.0,Friendly,London,England,False
2,1874-03-07,Scotland,England,2.0,1.0,Friendly,Glasgow,Scotland,False
3,1875-03-06,England,Scotland,2.0,2.0,Friendly,London,England,False
4,1876-03-04,Scotland,England,3.0,0.0,Friendly,Glasgow,Scotland,False

In [42]:
print(df.shape)

(49437, 9)

In [43]:
print(df.columns)

Index(['date', 'home_team', 'away_team', 'home_score', 'away_score',
       'tournament', 'city', 'country', 'neutral'],
      dtype='str')

In [44]:
df.sample(5)

,date,home_team,away_team,home_score,away_score,tournament,city,country,neutral
24433,2000-04-23,Egypt,Mauritius,4.0,2.0,FIFA World Cup qualification,Alexandria,Egypt,False
42082,2018-11-16,Saudi Arabia,Yemen,1.0,0.0,Friendly,Dammam,Saudi Arabia,False
26110,2001-12-16,Botswana,Lesotho,1.0,0.0,Friendly,Gaborone,Botswana,False
18936,1993-04-23,Egypt,Malawi,2.0,0.0,African Cup of Nations qualification,Alexandria,Egypt,False
44581,2021-10-12,Iran,South Korea,1.0,1.0,FIFA World Cup qualification,Tehran,Iran,False

In [45]:
df = df[[
    "date",
    "home_team",
    "away_team",
    "home_score",
    "away_score",
    "tournament"
]]

In [46]:
df.sample(5)

,date,home_team,away_team,home_score,away_score,tournament
22907,1998-07-19,Mozambique,Angola,1.0,1.0,COSAFA Cup
46456,2023-09-12,Morocco,Burkina Faso,1.0,0.0,Friendly
14554,1985-02-03,Uruguay,Paraguay,1.0,0.0,Copa Artigas
30654,2007-02-07,Croatia,Norway,2.0,1.0,Friendly
6894,1966-12-17,Thailand,Japan,1.0,5.0,Asian Games

In [47]:
def get_result(row):

    # Si l'équipe domicile marque plus
    if row["home_score"] > row["away_score"]:
        return 0

    # Si l'équipe extérieure marque plus
    elif row["home_score"] < row["away_score"]:
        return 2

    # Sinon match nul
    else:
        return 1

In [48]:
# Appliquer la fonction "get_result" à chaque ligne du DataFrame

In [49]:
df["result"] = df.apply(get_result, axis=1)

In [50]:
df.head()

         date home_team away_team  home_score  away_score tournament  result
0  1872-11-30  Scotland   England         0.0         0.0   Friendly       1
1  1873-03-08   England  Scotland         4.0         2.0   Friendly       0
2  1874-03-07  Scotland   England         2.0         1.0   Friendly       0
3  1875-03-06   England  Scotland         2.0         2.0   Friendly       1
4  1876-03-04  Scotland   England         3.0         0.0   Friendly       0

In [51]:
df["result"].value_counts()

result
0    24192
2    13948
1    11297
Name: count, dtype: int64

In [52]:
teams_stats = {}

In [53]:
for _, row in df.iterrows():

    home = row["home_team"]
    away = row["away_team"]

    if home not in teams_stats:
        teams_stats[home] = {
            "matches": 0,
            "wins": 0
        }

    if away not in teams_stats:
        teams_stats[away] = {
            "matches": 0,
            "wins": 0
        }

    teams_stats[home]["matches"] += 1
    teams_stats[away]["matches"] += 1

    if row["result"] == 0:
        teams_stats[home]["wins"] += 1

    elif row["result"] == 2:
        teams_stats[away]["wins"] += 1

In [54]:
teams_stats["France"]

{'matches': 937, 'wins': 476}

In [55]:
for team in teams_stats:

    matches = teams_stats[team]["matches"]
    wins = teams_stats[team]["wins"]

    teams_stats[team]["win_rate"] = wins / matches

In [56]:
teams_stats["France"]

{'matches': 937, 'wins': 476, 'win_rate': 0.5080042689434365}

In [57]:
def get_team_win_rate(team):
    return teams_stats[team]["win_rate"]

In [58]:
df["home_win_rate"] = df["home_team"].apply(get_team_win_rate)

df["away_win_rate"] = df["away_team"].apply(get_team_win_rate)