In [1]:
import pandas as pd
import numpy as np

print("Projet WC2026 ML lancé 🚀")

Projet WC2026 ML lancé 🚀

In [2]:
import pandas as pd
import numpy as np

# Charger le dataset
df = pd.read_csv("../data/results.csv")

# Afficher les 5 premières lignes
df.head()

,date,home_team,away_team,home_score,away_score,tournament,city,country,neutral
0,1872-11-30,Scotland,England,0.0,0.0,Friendly,Glasgow,Scotland,False
1,1873-03-08,England,Scotland,4.0,2.0,Friendly,London,England,False
2,1874-03-07,Scotland,England,2.0,1.0,Friendly,Glasgow,Scotland,False
3,1875-03-06,England,Scotland,2.0,2.0,Friendly,London,England,False
4,1876-03-04,Scotland,England,3.0,0.0,Friendly,Glasgow,Scotland,False

In [3]:
print(df.shape)

(49437, 9)

In [4]:
print(df.columns)

Index(['date', 'home_team', 'away_team', 'home_score', 'away_score',
       'tournament', 'city', 'country', 'neutral'],
      dtype='str')

In [5]:
df.sample(5)

,date,home_team,away_team,home_score,away_score,tournament,city,country,neutral
8944,1972-07-14,Malaysia,Philippines,1.0,0.0,Merdeka Tournament,Kuala Lumpur,Malaysia,False
49023,2025-11-26,Bahrain,Djibouti,1.0,0.0,Arab Cup qualification,Al Rayyan,Qatar,True
39659,2016-05-21,Abkhazia,Donetsk PR,0.0,0.0,Friendly,Sukhumi,Georgia,False
37187,2013-08-20,Afghanistan,Pakistan,3.0,0.0,Friendly,Kabul,Afghanistan,False
38981,2015-08-30,Niger,Burkina Faso,0.0,0.0,Friendly,Niamey,Niger,False

In [6]:
df = df[[
    "date",
    "home_team",
    "away_team",
    "home_score",
    "away_score",
    "tournament"
]]

In [7]:
df.sample(5)

,date,home_team,away_team,home_score,away_score,tournament
46731,2023-11-18,Anguilla,Bonaire,0.0,3.0,CONCACAF Nations League
16125,1988-05-04,Hungary,Iceland,3.0,0.0,Friendly
13253,1982-05-05,Denmark,Sweden,1.0,1.0,Nordic Championship
2908,1946-12-18,Venezuela,Guatemala,3.0,2.0,Central American and Caribbean Games
17731,1991-05-08,Martinique,DR Congo,0.0,0.0,Friendly

In [8]:
def get_result(row):

    # Si l'équipe domicile marque plus
    if row["home_score"] > row["away_score"]:
        return 0

    # Si l'équipe extérieure marque plus
    elif row["home_score"] < row["away_score"]:
        return 2

    # Sinon match nul
    else:
        return 1

In [9]:
# Appliquer la fonction "get_result" à chaque ligne du DataFrame

In [10]:
df["result"] = df.apply(get_result, axis=1)

In [11]:
df.head()

         date home_team away_team  home_score  away_score tournament  result
0  1872-11-30  Scotland   England         0.0         0.0   Friendly       1
1  1873-03-08   England  Scotland         4.0         2.0   Friendly       0
2  1874-03-07  Scotland   England         2.0         1.0   Friendly       0
3  1875-03-06   England  Scotland         2.0         2.0   Friendly       1
4  1876-03-04  Scotland   England         3.0         0.0   Friendly       0

In [12]:
df["result"].value_counts()

result
0    24192
2    13948
1    11297
Name: count, dtype: int64

In [13]:
teams_stats = {}

In [14]:
for _, row in df.iterrows():

    home = row["home_team"]
    away = row["away_team"]

    if home not in teams_stats:
        teams_stats[home] = {
            "matches": 0,
            "wins": 0
        }

    if away not in teams_stats:
        teams_stats[away] = {
            "matches": 0,
            "wins": 0
        }

    teams_stats[home]["matches"] += 1
    teams_stats[away]["matches"] += 1

    if row["result"] == 0:
        teams_stats[home]["wins"] += 1

    elif row["result"] == 2:
        teams_stats[away]["wins"] += 1

In [15]:
teams_stats["France"]

{'matches': 937, 'wins': 476}

In [16]:
for team in teams_stats:

    matches = teams_stats[team]["matches"]
    wins = teams_stats[team]["wins"]

    teams_stats[team]["win_rate"] = wins / matches

In [17]:
teams_stats["France"]

{'matches': 937, 'wins': 476, 'win_rate': 0.5080042689434365}

In [18]:
def get_team_win_rate(team):
    return teams_stats[team]["win_rate"]

In [19]:
df["home_win_rate"] = df["home_team"].apply(get_team_win_rate)

df["away_win_rate"] = df["away_team"].apply(get_team_win_rate)

In [20]:
df[[
    "home_team",
    "away_team",
    "home_win_rate",
    "away_win_rate",
    "result"
]].head()

  home_team away_team  home_win_rate  away_win_rate  result
0  Scotland   England       0.470726       0.571429       1
1   England  Scotland       0.571429       0.470726       0
2  Scotland   England       0.470726       0.571429       0
3   England  Scotland       0.571429       0.470726       1
4  Scotland   England       0.470726       0.571429       0

In [21]:
X = df[[
    "home_win_rate",
    "away_win_rate"
]]

y = df["result"]

In [22]:
X.head()

   home_win_rate  away_win_rate
0       0.470726       0.571429
1       0.571429       0.470726
2       0.470726       0.571429
3       0.571429       0.470726
4       0.470726       0.571429

In [23]:
y.head()

0    1
1    0
2    0
3    1
4    0
Name: result, dtype: int64