In [25]:
import pandas as pd
import numpy as np

print("Projet WC2026 ML lancé 🚀")

Projet WC2026 ML lancé 🚀

In [26]:
import pandas as pd
import numpy as np

# Charger le dataset
df = pd.read_csv("../data/results.csv")

# Afficher les 5 premières lignes
df.head()

,date,home_team,away_team,home_score,away_score,tournament,city,country,neutral
0,1872-11-30,Scotland,England,0.0,0.0,Friendly,Glasgow,Scotland,False
1,1873-03-08,England,Scotland,4.0,2.0,Friendly,London,England,False
2,1874-03-07,Scotland,England,2.0,1.0,Friendly,Glasgow,Scotland,False
3,1875-03-06,England,Scotland,2.0,2.0,Friendly,London,England,False
4,1876-03-04,Scotland,England,3.0,0.0,Friendly,Glasgow,Scotland,False

In [27]:
print(df.shape)

(49437, 9)

In [28]:
print(df.columns)

Index(['date', 'home_team', 'away_team', 'home_score', 'away_score',
       'tournament', 'city', 'country', 'neutral'],
      dtype='str')

In [29]:
df.sample(5)

,date,home_team,away_team,home_score,away_score,tournament,city,country,neutral
47125,2024-03-26,Georgia,Greece,0.0,0.0,UEFA Euro qualification,Tbilisi,Georgia,False
39261,2015-10-13,Qatar,Maldives,4.0,0.0,FIFA World Cup qualification,Doha,Qatar,False
9939,1974-11-05,Laos,Taiwan,1.0,2.0,Vietnam Independence Cup,Saigon,Vietnam Republic,True
44764,2021-11-16,Netherlands,Norway,2.0,0.0,FIFA World Cup qualification,Rotterdam,Netherlands,False
32524,2008-10-20,Malaysia,Afghanistan,6.0,0.0,Merdeka Tournament,Kuala Lumpur,Malaysia,False

In [30]:
df = df[[
    "date",
    "home_team",
    "away_team",
    "home_score",
    "away_score",
    "tournament"
]]

In [31]:
df.sample(5)

,date,home_team,away_team,home_score,away_score,tournament
34524,2011-02-08,Republic of Ireland,Wales,3.0,0.0,Nations Cup
30229,2006-09-02,Tanzania,Burkina Faso,2.0,1.0,African Cup of Nations qualification
28916,2004-12-21,Venezuela,Guatemala,0.0,1.0,Friendly
42123,2018-11-18,Hungary,Finland,2.0,0.0,UEFA Nations League
5052,1960-05-11,Germany,Republic of Ireland,0.0,1.0,Friendly

In [32]:
def get_result(row):

    # Si l'équipe domicile marque plus
    if row["home_score"] > row["away_score"]:
        return 0

    # Si l'équipe extérieure marque plus
    elif row["home_score"] < row["away_score"]:
        return 2

    # Sinon match nul
    else:
        return 1

In [33]:
# Appliquer la fonction "get_result" à chaque ligne du DataFrame

In [34]:
df["result"] = df.apply(get_result, axis=1)

In [35]:
df.head()

         date home_team away_team  home_score  away_score tournament  result
0  1872-11-30  Scotland   England         0.0         0.0   Friendly       1
1  1873-03-08   England  Scotland         4.0         2.0   Friendly       0
2  1874-03-07  Scotland   England         2.0         1.0   Friendly       0
3  1875-03-06   England  Scotland         2.0         2.0   Friendly       1
4  1876-03-04  Scotland   England         3.0         0.0   Friendly       0

In [36]:
df["result"].value_counts()

result
0    24192
2    13948
1    11297
Name: count, dtype: int64

In [37]:
teams_stats = {}

In [38]:
for _, row in df.iterrows():

    home = row["home_team"]
    away = row["away_team"]

    if home not in teams_stats:
        teams_stats[home] = {
            "matches": 0,
            "wins": 0
        }

    if away not in teams_stats:
        teams_stats[away] = {
            "matches": 0,
            "wins": 0
        }

    teams_stats[home]["matches"] += 1
    teams_stats[away]["matches"] += 1

    if row["result"] == 0:
        teams_stats[home]["wins"] += 1

    elif row["result"] == 2:
        teams_stats[away]["wins"] += 1

In [39]:
teams_stats["France"]

{'matches': 937, 'wins': 476}

In [40]:
for team in teams_stats:

    matches = teams_stats[team]["matches"]
    wins = teams_stats[team]["wins"]

    teams_stats[team]["win_rate"] = wins / matches

In [41]:
teams_stats["France"]

{'matches': 937, 'wins': 476, 'win_rate': 0.5080042689434365}

In [42]:
def get_team_win_rate(team):
    return teams_stats[team]["win_rate"]

In [43]:
df["home_win_rate"] = df["home_team"].apply(get_team_win_rate)

df["away_win_rate"] = df["away_team"].apply(get_team_win_rate)

In [44]:
df[[
    "home_team",
    "away_team",
    "home_win_rate",
    "away_win_rate",
    "result"
]].head()

  home_team away_team  home_win_rate  away_win_rate  result
0  Scotland   England       0.470726       0.571429       1
1   England  Scotland       0.571429       0.470726       0
2  Scotland   England       0.470726       0.571429       0
3   England  Scotland       0.571429       0.470726       1
4  Scotland   England       0.470726       0.571429       0

In [45]:
X = df[[
    "home_win_rate",
    "away_win_rate"
]]

y = df["result"]

In [46]:
X.head()

   home_win_rate  away_win_rate
0       0.470726       0.571429
1       0.571429       0.470726
2       0.470726       0.571429
3       0.571429       0.470726
4       0.470726       0.571429

In [47]:
y.head()

0    1
1    0
2    0
3    1
4    0
Name: result, dtype: int64

In [48]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

In [49]:
print(X_train.shape)
print(X_test.shape)

(39549, 2)
(9888, 2)